{% set name = "arraylake" %}
{% set version = "0.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arraylake-{{ version }}.tar.gz
  sha256: d3a19330b8e37b843cc3b36dd7bcd868977b8fe49264a0bd3bd67a0c0ce2cd04

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - arraylake = arraylake.cli.main:app
    - al = arraylake.cli.main:app

requirements:
  host:
    - python >=3.10,<3.13
    - hatchling
    - hatch-vcs
    - hatch-min-requirements
    - pip
  run:
    - packaging >=23.0
    - ruamel.yaml >=0.17,<1.0
    - python >=3.10,<3.13
    - aiobotocore >=2.10.0,<3.0
    - aioitertools >=0.11,<1.dev0
    - boto3 >=1.33.2,<2.0
    - botocore >=1.33.2,<2.0
    - click >=8.1,<9.dev0
    - donfig >=0.7,<1.0
    - email_validator >=2,<3
    - httpx >=0.23,<0.28
    - numpy >=1.23,<2.dev0
    - pydantic >=2.3,<2.10
    - python-dateutil >=2.8.0,<3.0.0
    - pyyaml >=6,<7.0
    - rich >=12.6,<14.0
    - ruamel.yaml >=0.17,<1.0
    - structlog >=24.1,<25.dev0
    - typer >=0.6.1,<1.0
    - uvloop <1.0,>=0.17  # [unix]
    - zarr >=2.18,<3.0
    - numcodecs >=0.13.1
    - __unix  # [unix]
    - __win   # [win]
    - cachetools >=5.3.2,<6.0
    - typing-extensions
    - fsspec >=2024.2.0
    - s3fs >=2024.02.0
    - gcsfs >=2024.2.0
    - sqlitedict >=2.1,<3.dev0
    - tenacity >=8.4.1,<9.0
    - humanize >=4.9.0,<4.10.dev0
    # https://github.com/conda/conda/issues/13619#issuecomment-2075825121
    - pyopenssl >=23.2.0
  run_constrained:
    - cfgrib >=0.9,<1
    - python-eccodes >=2.37.0
    - h5py >=3.7.0,<4.0.0
    - ipytree >=0.2.2,<1.0
    - kerchunk >=0.1,<1.0,!=0.2.1
    - tifffile >=2023.2.27
    - uvloop >=0.17,<1.0
    - xarray >=v2022.12.0
    - netcdf4 >=1.6.1,<1.7

test:
  imports:
    - arraylake
  commands:
    - pip check
    - arraylake --version
  requires:
    - pip

about:
  home: https://docs.earthmover.io
  summary: Python client for ArrayLake
  license: 'Unlicense'

extra:
  recipe-maintainers:
    - rabernat
    - jhamman
    - dcherian
    - monodeldiablo
    - lindseynield
