{% set name = "arraylake" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/arraylake-{{ version }}.tar.gz
  sha256: 32b28ae95bf6e30ae909fe86fc2f51f3762685b34a984da358cfe6e69c4f52ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - arraylake = arraylake.cli.main:app
    - al = arraylake.cli.main:app

requirements:
  host:
    - python >=3.8,<3.12
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
    - pip
  run:
    - python >=3.8,<3.12
    - aiobotocore >=2.4,<3
    - aioitertools >=0.11,<1
    - botocore >=1.31,<2
    - click >=8.1,<9
    - donfig >=0.7,<1.0
    - email_validator >=2,<3
    - httpx >=0.23,<1.0
    - numpy >=1.20,<2
    - pydantic >=1.10,<2
    - python-dateutil >=2,<3
    - pyyaml >=6,<7.0
    - rich >=12.6,<14.0
    - ruamel.yaml >=0.17,<1.0
    - structlog >=23.1,<24
    - typer >=0.6,<1.0
    - uvloop >=0.17,<1  # [unix]
    - zarr >=2.14,<=2.16
    - __unix  # [unix]
    - __win   # [win]
    - cachetools
    - typing-extensions
  run_constrained:
    - cfgrib >=0.9,<1
    - python-eccodes >=1.6.1,<2
    - fsspec >=2022.11.0
    - h5py >=3.7.0,<4.0.0
    - ipytree >=0.2.2,<1.0
    - kerchunk >=0.1,<1.0,!=0.2.1
    - s3fs >=2022.11.0
    - tifffile >=2023.2.27
    - uvloop >=0.17,<1.0
    - xarray >=v2022.12.0

test:
  imports:
    - arraylake
  commands:
    - pip check
    - arraylake --version
  requires:
    - pip

about:
  home: https://docs.earthmover.io
  summary: Python client for ArrayLake
  license: 'Unlicense'

extra:
  recipe-maintainers:
    - rabernat
    - jhamman
    - olimcc
    - dcherian
    - monodeldiablo
