{% set python_min = "3.11" %}
{% set name = "arraylake" %}
{% set version = "0.26.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/arraylake-{{ version }}.tar.gz
  sha256: 2202a12b150ac4a8de651c940bc89ca19380003f691ef5f9316b1761a6bed047

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - arraylake = arraylake.cli.main:app
    - al = arraylake.cli.main:app

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - hatch-min-requirements
    - pip
  run:
    - ruamel_yaml >=0.17,<1.0
    - python >={{ python_min }},<3.14
    - click >=8.1.3,<9.0
    - donfig >=0.7,<1.0
    - httpx >=0.23,<0.28
    - icechunk >=1.1.0,<2.0.0
    - numpy >=1.23,<3.0
    - packaging >=23.0,<26.0
    - pydantic >=2.9,<3.0
    - email-validator >=2.0.0
    - python-dateutil >=2.8,<3.0
    - rich >=12.6,<15.0
    - ruamel.yaml >=0.17,<1.0
    - structlog >=24.1,<26.0
    - typer >=0.12.0,<1.0
    - zarr >=3.1.0,<4.0
    - __unix  # [unix]
    - __win   # [win]
    # https://github.com/conda/conda/issues/13619#issuecomment-2075825121
    - pyopenssl >=23.2.0
  run_constrained:
    - xarray >=2024.10.0
    - cf_xarray >=0.10.4

test:
  imports:
    - arraylake
  commands:
    - pip check
    - arraylake --version
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://docs.earthmover.io
  summary: Python client for ArrayLake
  license: 'Unlicense'

extra:
  recipe-maintainers:
    - TomNicholas
    - rabernat
    - jhamman
    - dcherian
    - monodeldiablo
    - lindseynield
    - mpiannucci
